---
title: "Codebook - Rscript for Tidying UCI HAR Dataset"
author: "RoboRicky"
date: "11/13/2019"
output: html_document
---
### Features in UCI_HAR_Average_Mean_and_Std_Values_for_Subject-Activity_Pairs.txt

The features selected for this database come from averaging the mean and standard deviation measurements of accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ captured on 30 subjects performing 6 activities. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern in the X, Y and Z directions, and the set of measurements estimated from each of these signals and averaged are: 

mean(): Mean value
std(): Standard deviation
meanFreq(): Weighted average of the frequency components to obtain a mean frequency


So the full list of columns is as follows:

1. subject
2. activity
3. timeBodyAccelerometer-mean-X
4. timeBodyAccelerometer-mean-Y
5. timeBodyAccelerometer-mean-Z
6. timeBodyAccelerometer-standardDeviation-X
7. timeBodyAccelerometer-standardDeviation-Y
8. timeBodyAccelerometer-standardDeviation-Z
9. timeGravityAccelerometer-mean-X
10. timeGravityAccelerometer-mean-Y
11. timeGravityAccelerometer-mean-Z
12. timeGravityAccelerometer-standardDeviation-X
13. timeGravityAccelerometer-standardDeviation-Y
14. timeGravityAccelerometer-standardDeviation-Z
15. timeBodyAccelerometerJerk-mean-X
16. timeBodyAccelerometerJerk-mean-Y
17. timeBodyAccelerometerJerk-mean-Z
18. timeBodyAccelerometerJerk-standardDeviation-X
19. timeBodyAccelerometerJerk-standardDeviation-Y
20. timeBodyAccelerometerJerk-standardDeviation-Z
21. timeBodyGyroscope-mean-X
22. timeBodyGyroscope-mean-Y
23. timeBodyGyroscope-mean-Z
24. timeBodyGyroscope-standardDeviation-X
25. timeBodyGyroscope-standardDeviation-Y
26. timeBodyGyroscope-standardDeviation-Z
27. timeBodyGyroscopeJerk-mean-X
28. timeBodyGyroscopeJerk-mean-Y
29. timeBodyGyroscopeJerk-mean-Z
30. timeBodyGyroscopeJerk-standardDeviation-X
31. timeBodyGyroscopeJerk-standardDeviation-Y
32. timeBodyGyroscopeJerk-standardDeviation-Z
33. timeBodyAccelerometerMagnitude-mean
34. timeBodyAccelerometerMagnitude-standardDeviation
35. timeGravityAccelerometerMagnitude-mean
36. timeGravityAccelerometerMagnitude-standardDeviation
37. timeBodyAccelerometerJerkMagnitude-mean
38. timeBodyAccelerometerJerkMagnitude-standardDeviation
39. timeBodyGyroscopeMagnitude-mean
40. timeBodyGyroscopeMagnitude-standardDeviation
41. timeBodyGyroscopeJerkMagnitude-mean
42. timeBodyGyroscopeJerkMagnitude-standardDeviation
43. frequencyBodyAccelerometer-mean-X
44. frequencyBodyAccelerometer-mean-Y
45. frequencyBodyAccelerometer-mean-Z
46. frequencyBodyAccelerometer-standardDeviation-X
47. frequencyBodyAccelerometer-standardDeviation-Y
48. frequencyBodyAccelerometer-standardDeviation-Z
49. frequencyBodyAccelerometer-meanFrequency-X
50. frequencyBodyAccelerometer-meanFrequency-Y
51. frequencyBodyAccelerometer-meanFrequency-Z
52. frequencyBodyAccelerometerJerk-mean-X
53. frequencyBodyAccelerometerJerk-mean-Y
54. frequencyBodyAccelerometerJerk-mean-Z
55. frequencyBodyAccelerometerJerk-standardDeviation-X
56. frequencyBodyAccelerometerJerk-standardDeviation-Y
57. frequencyBodyAccelerometerJerk-standardDeviation-Z
58. frequencyBodyAccelerometerJerk-meanFrequency-X
59. frequencyBodyAccelerometerJerk-meanFrequency-Y
60. frequencyBodyAccelerometerJerk-meanFrequency-Z
61. frequencyBodyGyroscope-mean-X
62. frequencyBodyGyroscope-mean-Y
63. frequencyBodyGyroscope-mean-Z
64. frequencyBodyGyroscope-standardDeviation-X
65. frequencyBodyGyroscope-standardDeviation-Y
66. frequencyBodyGyroscope-standardDeviation-Z
67. frequencyBodyGyroscope-meanFrequency-X
68. frequencyBodyGyroscope-meanFrequency-Y
69. frequencyBodyGyroscope-meanFrequency-Z
70. frequencyBodyAccelerometerMagnitude-mean
71. frequencyBodyAccelerometerMagnitude-standardDeviation
72. frequencyBodyAccelerometerMagnitude-meanFrequency
73. frequencyBodyAccelerometerJerkMagnitude-mean
74. frequencyBodyAccelerometerJerkMagnitude-standardDeviation
75. frequencyBodyAccelerometerJerkMagnitude-meanFrequency
76. frequencyBodyGyroscopeMagnitude-mean
77. frequencyBodyGyroscopeMagnitude-standardDeviation
78. frequencyBodyGyroscopeMagnitude-meanFrequency
79. frequencyBodyGyroscopeJerkMagnitude-mean
80. frequencyBodyGyroscopeJerkMagnitude-standardDeviation
81. frequencyBodyGyroscopeJerkMagnitude-meanFrequency

### Features in Optional Outputs:

UCI_HAR_mean_meanFreq_and_std_values.csv (captured from Step 4) contains the same columns as UCI_HAR_Average_Mean_and_Std_Values_for_Subject-Activity_Pairs.txt, as it is the table of measurements that are to be averaged to produce the final output. It provides the measurements for each instance of the activity performed by the subject instead of the average measurement for an activity-subject pair. 

UCI_HAR_test_&_train_data_combined.csv (captured from step 1) contains all the features present in the original data as described in features_info.txt in the unzipped UCI HAR Dataset folder. The data has merely been consolidated from the test and train files and the feature columns labeled from the feature list. 
